FROM python:3.12-slim

WORKDIR /app
COPY services/resource-service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY services/resource-service /app
COPY resources /app/resources

EXPOSE 8004
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004"]

